config/routes.rb
UrlShort::Application.routes.draw do
  devise_for :users

  resources :url_resources, :only => [:new, :create, :show, :index]
  match ':id' => 'url_resources#short', :as => :short
  root :to => 'pages#landing'
end

app/models/url_resource.rb
class UrlResource < ActiveRecord::Base
  
  attr_accessible :url_string

  serialize :browsers, Hash

  validates :url_string, :format => URI::regexp(%w(http https))
  validates_uniqueness_of :token

  before_validation  :generate_token

  belongs_to :user

  def generate_token
    loop do 
      token = SecureRandom.base64(6).tr('+/=lIO0', 'pqrsxyz')
      break self.token = token unless UrlResource.find_by_token(token)
    end
  end

  def increase_browser_count(browser)
    self.browsers[browser] = self.browsers[browser] + 1 rescue 1
    self.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :url_resources
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/url_resources_controller.rb
class UrlResourcesController < ApplicationController

  before_filter :authenticate_user!, :only => [:index, :show, :new, :create]

  def index
    @url_resources = current_user.url_resources
  end

  def show
    begin
      @url_resource = current_user.url_resources.find(params[:id])
    rescue
      redirect_to url_resources_path, :flash => { :error => "Url not found" }      
    end
  end

  def new
    @url_resource = UrlResource.new
  end

  def create
    @url_resource = UrlResource.find_or_create_by_url_string(params[:url_resource])
    @url_resource.user = current_user
    if @url_resource.save
      redirect_to @url_resource, :flash => { :notice => "Url Created" }
    else
      render :new
    end
  end

  def short
    if @url_resource = UrlResource.find_by_token(params[:id])
      @url_resource.increase_browser_count browser.name
      redirect_to @url_resource.url_string
    else
      redirect_to :root, :flash => { :error => "Url not found" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/url_resources_helper.rb
module UrlResourcesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UrlShort
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Url Shortener", root_path, :class => "brand"
          .nav-collapse.collapse
            %ul.nav

              %li{controller.action_name == "landing" && :class => "active"}
                = link_to "Home", root_path
              - if user_signed_in?
                %li{(controller.action_name == "index" && controller.controller_name == "url_resources") && :class => "active"}
                  = link_to "My Urls", url_resources_path
                %li{(controller.action_name == "new" && controller.controller_name == "url_resources") && :class => "active"}
                  = link_to "Add Url", new_url_resource_path
            - unless user_signed_in?
              = simple_form_for :user, :url => user_session_path, :html => { :class => 'navbar-form pull-right' } do |f|
                = f.text_field :email, :label => false, :placeholder => "Email", :class => "span2"
                = f.password_field :password, :label => false, :placeholder => "Password", :class => "span2"
                = f.submit "Sign in", :class => "btn"
                =link_to "Sing Up", new_user_registration_path, :class => "btn btn-primary"
            - else
              =link_to "Log Out", destroy_user_session_path, :class => "btn btn btn-danger pull-right", :method => :delete
          / /.nav-collapse
    .container
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"} x
          = msg
      = yield

app/views/pages/landing.haml
.hero-unit
  %h1
    Welcome
  Signup today to use this incredible url shortener
  %p
    =link_to "Sing Up", new_user_registration_path, :class => "btn btn-primary"
.row
  .span4
    %h2
      Great Feature
    %p
      Pulvinar nascetur porttitor dis lacus adipiscing! In ut amet sit. Mauris? Porta, non ac nisi elit cursus enim non nec dis ultricies? Scelerisque? Velit non porttitor elementum placerat cum sed, turpis, penatibus? Et pulvinar porta duis etiam penatibus penatibus proin habitasse augue enim nec non, diam est magna montes, mauris hac, in sed aenean. Porttitor dignissim, urna, odio phasellus, integer? Aenean pulvinar aliquam, tristique sociis, rhoncus arcu duis rhoncus augue, vel diam scelerisque et porta nascetur parturient, turpis duis parturient, amet quis turpis enim facilisis nisi et amet? Sit eu.
  .span4
    %h2
      Great Feature
    %p
      Scelerisque, sociis parturient et scelerisque nec ridiculus, odio tristique? Ut! Augue. Eros pellentesque, quis dapibus facilisis turpis! Eu penatibus! Aenean lectus! Etiam ut? Penatibus cursus porta hac integer a, proin, magna cras aliquet odio tristique ultrices placerat sit placerat pulvinar in placerat, massa. Pulvinar cursus dolor turpis, turpis lacus, placerat mus tempor elementum! Enim? Rhoncus turpis et ut a adipiscing rhoncus nascetur massa phasellus ut, dictumst penatibus odio velit in lundium lectus odio adipiscing ridiculus parturient vel. Platea. Velit, ac cum. Vel nec tortor tristique! Placerat urna purus sociis.
  .span4
    %h2
      Great Feature
    %p 
      Mattis dapibus cum turpis mattis tortor! Urna amet urna ut integer, dictumst dictumst egestas, tincidunt! Nec nunc habitasse ac, odio aliquet et duis, scelerisque. Porta, ac tincidunt nisi, arcu, vut etiam rhoncus vel ultrices nascetur, aenean ultricies in in sagittis odio, turpis lectus risus. Arcu egestas in duis vut ultrices, ut sit lectus urna odio etiam ac ultrices augue, a habitasse, et proin magnis sagittis ut elit mauris, in elit augue? In elementum vel tortor! Lundium tincidunt. Dapibus. Quis, sagittis porta sed scelerisque, hac amet! Mattis rhoncus elementum enim.

app/views/url_resources/index.haml
%h1 My Urls
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Url
      %th Short Url
      %th Created at
  %tbody
    - @url_resources.each do |url_resource|
      %tr
        %td= link_to url_resource.id, url_resource_path(url_resource)
        %td= url_resource.url_string
        %td= short_url(url_resource.token)
        %td= url_resource.created_at

app/views/url_resources/new.haml
= simple_form_for @url_resource, :html => { :class => 'form-url' } do |f|
  %h2
    Enter Url
  %fieldset  
    = f.input :url_string, :label => false
    .control-group
      .controls
        = f.submit "Add Url", :class => "btn"

app/views/url_resources/show.haml
%h1
  Resource
%p
  %b
    Url
    %br
  = link_to @url_resource.url_string, @url_resource.url_string
%p
  %b
    Short Url
    %br
  = link_to short_url(@url_resource.token), short_path(@url_resource.token)
%p
  %b
    Browser
    %br
  - @url_resource.browsers.each do |browser|
    %i
      = browser[0]
    = pluralize browser[1], 'visit'
    %br